### ISSUE TITLE
Grundsätzliches

### ISSUE THREAD

**Issue by bauepete** [IxI-Enki/Uebung-syp-002#2]
In Ihrer Arbeit ist wirklich schon sehr viel spannendes zu lesen. 

I) und II) sind schon eine recht brauchbare Version einer Ausgangssituation und der Rahmenbedingungen

Bei III) würde ich mich auf Ihre Lösungsidee beschränken und diese noch sehr viel konkreter machen

IV) Die Konkurrenz würde ich in die Ausgangssituation einbauen

Man sieht, dass Sie bereits einiges an Nachdenken in diese Idee investiert haben und bereits recht sorgfältig gearbeitet haben.

Die Aussagen, die Sie tätigen sind an manchen Stellen aber noch zu vage. Beispiele:
- "manche Dinge sind aber einfach nicht miteinander vereinbar"; was meinen Sie konkret? Wie steht das im Zusammenhang mit Ihrer Projektidee?
- "Die gefundenen Informationen einordnen"; der gesamte Absatz macht hauptsächlich Andeutungen, die wiederum nur schwer in Ihren Projektkontext einordenbar sind. Sie schreiben "... schränken das Benutzererlebnis bis zur Abschreckung ein". Was meinen Sie damit? Man bezahlt, dann ist man dabei, wenn nicht, dann nicht. Was ist daran abschreckend? Meinen Sie, dass es Benutzer:innen vom Informationsangebot ausschließt? Das würde ich verstehen. "um eine erste Filterung der Inhalte zu erreichen und die Richtung dieser etwas vorzugeben oft sind diese (absichtlich) schwammig, missverständlich und unterliegen nicht selten drastischen Änderungen"; ich verstehe den ganzen Satz nicht (meiner Meinung nach nicht Deutsch). Auch würde ich mir sehr konkrete Beispiele wünschen. Sie fahren hier doch sehr scharfe Geschütze auf. Da brauchen Sie schon sehr konkrete Beispiele, um das zu untermauern. "... um unbequeme Menschen/... von der Plattform zu tilgen"; auch hier ist das eine recht heftige Unterstellung, die Sie nicht ohne Beweis in den Raum stellen können. Dass es grundsätzlich Richtlinien gibt werden Sie ja wohl nicht angreifen wollen, oder? Dass sich eine Plattform vor rassistischen, etc. Inhalten schützen will, ist wohl alleine aus juristischer Sicht nachvollziehbar.

**Comment by IxI-Enki** [comment]
tried my best

**Comment by IxI-Enki** [comment]
now fact-based

[version 0.2.9](https://github.com/IxI-Enki/education-hub/blob/jan/EducationHub.md)
