### ISSUE TITLE
Schriftarten, -farben und Formulierungen

### ISSUE THREAD

**Issue by bauepete** [IxI-Enki/Uebung-syp-002#3]
Ein Project Proposal soll (im Gegensatz zu einer Werbebroschüre) mit Fakten und einer auf Emotionen verzichtenden Sprache ausgeführt sein. Dazu gehört auch, dass man auf "kreative" Schriftwahl und -farbe verzichten soll.

Manche Sätze sind auch mehr in Werbebroschüren-Diktion gehalten. Beispiel: "Einfach: Videos, Texte, Dokumente, Präsentationen einfügen oder interaktive Frage-Antwort-Spiele gestalten.
die Möglichkeiten sind nahezu grenzenlos" Dafür würde ich nicht mal 50 cent rausrücken, weil ich nur höre, dass Sie noch keine Idee haben, wie diese Grenzenlosigkeit aussieht, oder wie sie sich von bereits bestehenden Plattformen unterscheidet.

**Comment by IxI-Enki** [comment]
@DBsMOJO

**Comment by IxI-Enki** [comment]
did it 
[better 0.2.9](https://github.com/IxI-Enki/education-hub/blob/jan/EducationHub.md#ⅲ--die-lösung-educationhub---der-umschlagplatz-für-bildung)
