### ISSUE TITLE
Finanzierungskonzept nicht gefunden

### ISSUE THREAD

**Issue by bauepete** [IxI-Enki/Uebung-syp-002#4]
Sie schreiben "Eine ständige Administration und Weiterentwicklung erfordern nicht nur technische, sondern auch finanzielle Ressourcen." Insgesamt sehe ich den größten Hacken bei Ihrem Vorschlag, dass ich nicht den Funken einer Idee habe, wie Sie das finanzieren wollen und dem Leser auch keine eigene Idee dazu anbieten.

**Comment by IxI-Enki** [comment]
[Finanzierung 0.1](https://github.com/IxI-Enki/education-hub/blob/jan/EducationHub.md#-budget-)

**Comment by IxI-Enki** [comment]
[Finances 0.2.9](https://github.com/IxI-Enki/education-hub/blob/jan/EducationHub.md#3-finanzierung)
